repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: local
  hooks:
    - id: make-fmt
      name: make fmt
      entry: make fmt
      language: system
      files: \.go$
      pass_filenames: false

    - id: make-vet
      name: make vet
      entry: make vet
      language: system
      files: \.go$
      pass_filenames: false

    - id: make-lint
      name: make lint
      entry: make lint
      language: system
      files: \.go$
      pass_filenames: false

    - id: make-test
      name: make test
      entry: make test
      language: system
      files: \.go$
      pass_filenames: false
